# Generated by Django 5.2 on 2025-05-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_student_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cdescription', models.CharField(max_length=200)),
                ('cdurition', models.CharField(max_length=200)),
                ('cid', models.IntegerField(max_length=20)),
            ],
        ),
    ]
