# Generated by Django 5.2 on 2025-05-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.IntegerField(max_length=200),
        ),
    ]
